FROM python:3.8-alpine

# Make dir app
RUN mkdir /app
WORKDIR /app

# Copy the source from the current directory to the Working Directory inside the container
COPY * /app/
COPY ../libs/shared /app/

# Install dependencies
RUN pip3 install -r requirements.txt

# Expose port 8080 to the outside world
EXPOSE 8080

# Run the executable
CMD ["python3", "main.py"]